### PR TITLE
Update ReadMe

### PR DESCRIPTION
**Pull request by DanRStevens**
My attempt at improving and modernizing the ReadMe.

### CODE REVIEW

**Review by Brett208 — APPROVED** [review]
Looks good. 

I would okay removing the 'use at your own risk' paragraph. 

Also, I would be fine removing the what you see is what you get paragraph. I think forum users would be willing to help fix bugs as asked and I wouldn't want to encourage people not to report issues if they feel no one will care or help to fix.

-Brett

**Comment by DanRStevens** [comment]
Good point. I like your suggestions.

**Comment by DanRStevens** [comment]
Just noticed a moral dilemma concerning the signature line. Thought I should get your opinion on that before merging.

**Comment by Brett208** [comment]
Yeah, I think that is a good call. It still recognizes the original author without implying they 100% agrees with the changes of the readme (or the rest of the codebase as we move forward and that have been made earlier).

**Pull request merged**
